# Generated by Django 5.1.6 on 2025-02-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_active_lising_creator_alter_bids_listing_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing',
            new_name='watchlist',
        ),
    ]
